### ISSUE TITLE
Incompatibility with timvink/mkdocs-git-revision-date-localized-plugin

### ISSUE THREAD

**Issue by pauloribeiro-codacy** [spotify/mkdocs-monorepo-plugin#12]
Hello,

I was trying to use the MkDocs plugin [timvink/mkdocs-git-revision-date-localized-plugin](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) in my project but it always fails with:

```
$ mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/prcr/Codacy/git/docs/site 
ERROR   -  Unable to read git logs of '/tmp/docs_kvh_ua8a/index.md'. To ignore this error, set option 'ignoring_missing_git: true'
ERROR   -  Error reading page 'index.md': Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 /tmp/docs_kvh_ua8a/index.md
  stderr: 'fatal: /tmp/docs_kvh_ua8a/index.md: '/tmp/docs_kvh_ua8a/index.md' is outside repository' 
[...]
```

I was able to pinpoint the issue to the fact that I'm using mkdocs-monorepo-plugin as well. It seems that the plugin copies the *.md files to a temporary directory before building them, and this way the other plugin cannot use `git log` to find out the last updated date of the Markdown files.

**Comment by timvink** [comment]
I see that `mkdocs-monorepo-plugin`  copies the contents of multiple `docs/` dirs into a temporary `docs_/` directory at the MkDocs event `on_config()`.

`mkdocs-git-revision-date-localized-plugin` uses the event `on_page_markdown()`, and then specifically the `page.file.abs_src_path` attribute of a page.

One possible solution might be to use symlinks to the temporary `docs_/` folder instead of copying files. That way hopefully the `abs_src_path` remains intact. So replace:

https://github.com/spotify/mkdocs-monorepo-plugin/blob/3cf93fa0d433a35f3d850ffa13de2d00462e3f68/mkdocs_monorepo_plugin/merger.py#L59

with:

```python
copytree(source_dir, dest_dir, symlinks=True)
```

I haven't tested this yet, but I am willing to give it a try and provide a PR?

**Comment by bih** [comment]
@timvink That sounds like an interesting approach and definitely has pros compared to how we do it today of constructing a new `docs/` directory in the `/tmp` temporary filesystem. Looking forward to seeing what your approach is and happy to provide feedback :)

**Comment by timvink** [comment]
Cool, will pick this up somewhere in next week!

**Comment by timvink** [comment]
The symlink approach didn't work, but I got it working with the second idea. Opened https://github.com/spotify/mkdocs-monorepo-plugin/pull/13, let's discuss details there!
