### ISSUE TITLE
Incompatible with mkdocs version 1.1.1

### ISSUE THREAD

**Issue by rossmechanic** [spotify/mkdocs-monorepo-plugin#15]
https://github.com/mkdocs/mkdocs/commit/7b68f7b828f29dffe2603117660bb9442d9348a3

The commit above breaks integrations between this library and mkdocs. 

Pretty sure it would be fixed by updating this line
https://github.com/spotify/mkdocs-monorepo-plugin/blob/master/mkdocs_monorepo_plugin/plugin.py#L54

to include kwargs. thoughts?

**Comment by emmaindal** [comment]
Hey @rossmechanic thanks for reporting this - as you maybe know already and mention in the title of your issue this is not a breaking change at the moment since we have not upgraded to version 1.1.1 of mkdocs yet. But when we do, we of course want it to not break anything so we are super happy you found this! 

Would be awesome if you want to open a PR with your changes and we will look in to it more! 😃

**Comment by rossmechanic** [comment]
@emmaindal super simple pr: #16
